### PR TITLE
added Gromov-Hausdorff distance

### PR DESCRIPTION
**Pull request by vlad-oles**
Added implementation of the modified Gromov-Hausdorff distance between unweighted graphs and metric spaces of integer distances in general. Haven't reflected this in documentation as the latter only regards distances between persistence diagrams, which are not unweighted graphs — so wasn't sure about the context in which I should describe the new distance.

### CODE REVIEW

**Comment by ctralie** [comment]
Woah nice, I wasn't aware that there was a general version of the Gromov-Hausdorff distance whose bound could be computed in polynomial time.  I'll have to have a look at the reference.  Yes, @sauln we'll have to think of whether this fits into persim or somewhere else.  But thank you so much @vlad-oles!

**Comment by ctralie** [comment]
Actually, I think this should be promoted to its own project within scikit-tda.  Since it operates on two (integer) distance matrices, it's as general as (e.g.) ripser.py.  Thoughts @sauln?

**Comment by sauln** [comment]
@ctralie, I think you're right that it transcends the current scope of persim, but I'm reluctant to add many more packages if we can avoid it. The overhead of dealing with pypi and docsite coordination is already becoming a pain point.

When talking with Vlad a few weeks ago, my thought was that we could expand persim again to include any distances of interest to TDA community.  For instance, I'd like to include some of the distances on Mapper discussed [here](https://arxiv.org/abs/1812.06232). 

What are your thoughts on this?

**Comment by ctralie** [comment]
Okay yeah that sounds reasonable

**Comment by vlad-oles** [comment]
@ctralie The paper by Memoli I reference in the source only defines the (modified Gromov-Hausdorff) distance. Polynomial algorithm for bounding it is the subject of my ongoing paper that I am to finish in 1-2 months — as of now, it needs more computational examples. My main contribution is the algorithm for (tight) lower bound. Upper bound then is obtained by a common heuristic method for Quadratic Bottleneck Assignment formulation of the distance, aimed to match the lower bound. I'll be happy to share a draft of the paper.

@sauln After looking at persim more closely I can see how Gromov-Hausdorff might not be a fit, but I'd leave it at your discretion, as I know quite little about packaging.

I'm currently looking to replace `pyscipopt` with another tool to solve Bottleneck Transportation optimization, since the package requires installing the SCIP Optimization Suite, a standalone software package. Given the scarcity of solver options so far, there is some chance I'll end up writing it myself.

**Comment by vlad-oles** [comment]
@sauln @ctralie Sorry I forgot to follow up. Just added another commit with minor refactoring. Could you please merge?

**Comment by sauln** [comment]
Hey Vlad, sorry for moving slow on this. Been swamped this spring. 

What is the state of the documentation? I see some nice docstrings, do you have any examples? Adding a couple of examples to the file doctoring would be helpful. In particular one that starts with a networkx graph or distance matrix, i.e. shows how to build the expected graph format.

**Comment by vlad-oles** [comment]
No worries Nathaniel. I've just added few usage examples to the file docstring. Let me know if this will do for now.

Currently the script only takes adjacency matrices as the input, whether in dense or sparse formats.

**Comment by sauln** [comment]
Those updates look great.  Final change, sorry to be nitpicky: could you format the code snippets in RST format so the docs site will render them correctly?

It should be fine to either have line start with an `>>>`, or have the block start with an `::` (like [this](https://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/ShowingCodeExamplesInSphinx.html))

It would also be nice to have the output shown on one or two of the examples:

```
>>> A_G = [[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0, 0, 0, 0]]
>>> A_H = [[0]]
>>> lb, ub = gromov_hausdorff_between_graphs(A_G, A_H)
>>> lb, ub
(2.4, 5.6)
```

(note, I just made up the values printed above).

**Comment by vlad-oles** [comment]
NP, I'm happy to learn about the documentation standards. Please let me know if this looks good or if any other updates are needed.

**Comment by sauln** [comment]
Great! It would really helpful if you tested how sphinx renders your docstrings. 

You can test how the docs render by:

```
pip install -e ".[docs]"
cd docs
make html
```

then open `build/html/index.html` in a browser.  

You'll probably have to add a line or two [in this file](https://github.com/scikit-tda/persim/blob/master/docs/reference/index.rst) so sphinx looks for your function.

**Comment by vlad-oles** [comment]
Thanks, the distance is now showing in "API Reference". I've also shortened `gromov_hausdorff_between_graphs` to `gromov_hausdorff` for now, as the former was ruining the layout of "Table of Contents".

**Pull request merged**
