### PR TITLE
Made `ax` arg for plot functions actually be used.

### PR DESCRIPTION
**Pull request by mmcdermott**

### CODE REVIEW

**Comment by sauln** [comment]
Good catch!   Could you add a clause at the top of the function to set ax if it isn't passed in?  I've seen something like this work in the past:
```
ax = ax or plt.gca()
```

**Comment by mmcdermott** [comment]
yep, will do!

**Comment by mmcdermott** [comment]
I think it is working now? Let me know if it needs any modifications though @sauln

**Comment by sauln** [comment]
Looks good. Thanks for your contribution ❤️

**Pull request merged**
