### PR TITLE
Add persistence landscape functionality

### PR DESCRIPTION
**Pull request by calderds**
Created function `persim.to_landscape(diagram)` that converts a persistence diagram into a persistence landscape. Initial functionality works - see `demo/landscape_demo.py` for a simple example - but any and all feedback is welcome!

### CODE REVIEW

**Comment by calderds** [comment]
20201226 - add plot_landscape() function to plot landscapes. Needs work on implementing full plotting power.

**Comment by ctralie** [comment]
Hello, thank you for your work on this, and my apologies for the lag in our
response to this!

Part of the reason for the lag is that we're actually working to integrate
a different persistence images library into scikit-tda
https://github.com/gabbyangeloro/Masters_Thesis
but I am curious to hear your opinion on that
Sincerely,
Chris Tralie

**Comment by calderds** [comment]
Hi Chris, 
The version you linked has much more thought put into it than mine :) I'd be happy to help integrate this code into the existing persim! 

The only suggestion that comes to mind right now is to potentially incorporate my plot_landscape() function somewhere to provide a "simpler" 2D plot, as opposed to the 3D version in the linked repo. Interested to hear your opinion on this. 

Calder

**Comment by calderds** [comment]
Closing PR for Pyscapes integration

**Pull request closed without merging**
