### PR TITLE
Fix pl plotting

### PR DESCRIPTION
**Pull request by catanzaromj**
This PR fixes numerous bugs with plotting persistence landscapes. In particular

- user specified labels for coordinate axes now work,
- doc strings are cleaned up and now on publicly accessible methods,
- added a `depth_range` parameter so a subset of landscape functions can be plotted,
- `padding` previously incorrectly changed landscape function values,
- updated 3d axes call to remove deprecation error.

A `max_depth` attribute has also been added to `PersLandscapeApprox` and the notebooks were updated.

Please pass along any comments you have. Thanks.

### CODE REVIEW

**Comment by sauln** [comment]
Hi @catanzaromj, these changes look great.  Once the tests are passing we can merge.  Though it looks like the test failure might be unrelated, you should be able to fix it using `numpy.testing.assert_almost_equal`. 

Thank you!

**Comment by catanzaromj** [comment]
No problem. Let me know if there's anything else. Thanks!

**Comment by catanzaromj** [comment]
@sauln Is there anything else needed?

**Comment by catanzaromj** [comment]
The test coverage dropping will be covered in a future PR.

**Pull request merged**
